### PR TITLE
added highlighting of matched output on selection in console

### PR DESCRIPTION
**Pull request by CapelliC**
first attempt to resume collaboration after migration to github :)

### CODE REVIEW

**Comment by CapelliC** [comment]
added functionality and fixed a bug

**Comment by JanWielemaker** [comment]
Hmm.  Old version compiled file, but now I get:

```
g++ -c -m64 -pipe -std=c++0x -O2 -fno-strict-aliasing -pthread -fPIC -Wall -W -D_REENTRANT -fPIE -DPQCONSOLE_STATIC -DPL_SAFE_ARG_MACROS -DPQCONSOLE_NO_HTML -DPQCONSOLE_BROWSER -DPQCONSOLE_HANDLE_HOOVERING -DLQUTY_STATIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I../../../../lib/swipl/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -o main.o main.cpp
main.cpp: In function ‘void logger(QtMsgType, const QMessageLogContext&, const QString&)’:
main.cpp:88:10: error: ‘QtInfoMsg’ was not declared in this scope
     case QtInfoMsg:
          ^
make: *** [main.o] Error 1
```

P.s.     Normally I'm the one closing a pull request after merging or the submitter closes it after discovering the request was not a good idea.

**Comment by CapelliC** [comment]
I'm using Qt 5.5, and I removed a warning issued about the missing enum ...
I'll bracket the change the with the appropriate QT_VERSION then.

2015-10-03 13:26 GMT+02:00 Jan Wielemaker notifications@github.com:

**Comment by JanWielemaker** [comment]
Thanks.  Works.   Merged.  Not sure what the matching parenthesis does though.  I'd expected it to
highlight the matching bracket, but I see no difference.

**Comment by CapelliC** [comment]
thanks Jan

It's intended to highlight matched output, so it help to find variables
occurrences in traces. I found useful when debugging CLP(FD).
I don't have right now an example ready... but to give an idea...

​
Highlighting matching braces on input console it's ready, since the code to
highlight blocks is already merged now (I had it as utility in class
ParenMatching).
Just I should attach the proper event handler. I will issue another pull
request, if doesn't hurt...

2015-10-04 18:02 GMT+02:00 Jan Wielemaker notifications@github.com:

**Comment by JanWielemaker** [comment]
Ok.  Please test ...

**Pull request merged**
